### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [nuxeo/nuxeo-drive#1013]
Where can the AppImage for Linux be downloaded? Unfortunately I cannot seem to find it on GitHub Releases.

**Comment by BoboTiG** [comment]
Wow, you are fast!

The file is not yet in public access as there is still some work to do ([https://jira.nuxeo.com/browse/NXDRIVE-1408](NXDRIVE-1408)), but I will find a way to link it in the thread.

For the future, il will be available on [https://community.nuxeo.com/static/drive-updates/](https://community.nuxeo.com/static/drive-updates/).

As it is missing some critical fixes, you should start it like:
```bash
./nuxeo-drive-4.1.4-x86_64.AppImage --ssl-no-verify
```

**Comment by BoboTiG** [comment]
This is the download link: [nuxeo-drive-4.1.4-x86_64.AppImage](https://send.firefox.com/download/db93b1ef6f17a7a9/#a-fXBGxAla4cvSIY09jfqw).

**Comment by probonopd** [comment]
Thank you very much. Please ping me once a released version that does not need the workaround is available, so that I can run the tests on https://github.com/AppImage/appimage.github.io/ and add it to the catalog. Thanks for choosing AppImage!

**Comment by BoboTiG** [comment]
Sure, I plan to work on it the next weeks. AppImage is really cool, so thank you ;)
I see in your link that I will have more work to pass all requirements, but it wil be great to be part of the catalog.

**Comment by BoboTiG** [comment]
Hey @probonopd,

The AppImage is now clean and working. It passes all required steps and can be found at that persistent URL: https://community.nuxeo.com/static/drive-updates/nuxeo-drive-x86_64.AppImage (the link is also available on each GitHub release notes).

I successfully tested it on:
- Debian GNU/Linux 10
- Ubuntu 16.04, 18.04 and 19.04
- Fedora 29 and 30
- Manjaro Linux 18.1.0

Let me know if some more work is needed from our side :)
