### ISSUE TITLE
Screencast link on README links to a 404

### ISSUE THREAD

**Issue by adamtheturtle** [nuxeo/nuxeo-drive#108]
In the title section of the README (https://github.com/nuxeo/nuxeo-drive/blob/master/README.md#nuxeo-drive---desktop-synchronization-client-for-nuxeo) there is a link to a screencast. This links to https://www.nuxeo.com/blog/development/2013/04/nuxeo-drive-desktop-synchronization/.

I'm not sure exactly what this should link to - perhaps the video on https://www.nuxeo.com/products/drive-desktop-sync/, else I'd submit a PR.

I've also had success using http://wummel.github.io/linkchecker/ with CI to catch this class of error.

**Comment by ataillefer** [comment]
Thanks Adam, indeed the link needed to be updated, just fixed it.
And noted about the link checker tool!
