### ISSUE TITLE
Bug in Drive for Windows EXE Arguments.

### ISSUE THREAD

**Issue by altjones** [nuxeo/nuxeo-drive#1898]
Possible Bug in Drive for Windows EXE Arguments.
Using this tutorial https://doc.nuxeo.com/client-apps/how-to-manually-initialize-or-deploy-a-nuxeo-drive-instance/ I've installed Drive for Windows with the EXE variables below…

```
nuxeo-drive.exe /VERYSILENT /TARGETDRIVEFOLDER="%USERPROFILE%\Documents\Nuxeo Drive" /TARGETURL="http://localhost:8080/nuxeo" /TARGETUSERNAME="foo"
```

The `TARGETURL` has been modified to reflect our environment.

I've selected these variables so when we mass deploy the Drive application the user does not need to know and enter our Nuxeo url.

The issue I'm seeing is when you go to the Accounts settings page you see the Username as “foo” (or whatever you enter in the EXE argument).

Once you log back in, the “foo” name stays in the username field. It never changes to the actual username of the re-authenticated user.

It's only a visible issue and does not affect the operation of the Drive app, but it's one that could confuse our support staff if they need to troubleshoot and see a different name in the username field.

**Comment by BoboTiG** [comment]
Hello,

I think this is the same message as [here](https://answers.nuxeo.com/general/q/a0eb2ca6ce5345779f6f1158b14d291d/Possible-Bug-in-Drive-for-Windows-EXE-Arguments), right?

Thank you, we will reproduce and fix the issue quickly :)

**Comment by altjones** [comment]
That is correct.

**Comment by BoboTiG** [comment]
Out of curiosity: could you open a SUPCOM also? It will help priorityzing the issue more quickly.

**Comment by altjones** [comment]
> Out of curiosity: could you open a SUPCOM also? It will help priorityzing the issue more quickly.

Not sure what a SUPCOM is.

**Comment by BoboTiG** [comment]
It is a customer suppor tticket: https://jira.nuxeo.com/browse/SUPNXP.

**Comment by BoboTiG** [comment]
I created https://jira.nuxeo.com/browse/NXDRIVE-2272, it will be done for the next release.

**Comment by BoboTiG** [comment]
The fix will be part of the alpha version of tomorrow, if you mind testing. You can find such version here: https://community.nuxeo.com/static/drive-updates/alpha/.
