### ISSUE TITLE
nuxeo drive from master or 5.9.5 does not create ndrive on ubuntu 16.04

### ISSUE THREAD

**Issue by baradhili** [nuxeo/nuxeo-drive#297]
Hi,
running install as per tag 5.9.5 completed without failures, however ndrive does not exist afterwards.
Parts are there, but not the application

eg.
$ locate ndrive
/usr/local/lib/python2.7/dist-packages/nxdrive/data/ui5/css/ndrive.css
/usr/local/lib/python2.7/dist-packages/nxdrive/data/ui5/js/ndrive-conflicts.js
/usr/local/lib/python2.7/dist-packages/nxdrive/data/ui5/js/ndrive-modal.js
/usr/local/lib/python2.7/dist-packages/nxdrive/data/ui5/js/ndrive-network-error.js
/usr/local/lib/python2.7/dist-packages/nxdrive/data/ui5/js/ndrive-settings.js
/usr/local/lib/python2.7/dist-packages/nxdrive/data/ui5/js/ndrive-systray.js
/usr/local/lib/python2.7/dist-packages/nxdrive/data/ui5/js/ndrive.js
/usr/local/ui5/css/ndrive.css
/usr/local/ui5/js/ndrive-conflicts.js
/usr/local/ui5/js/ndrive-modal.js
/usr/local/ui5/js/ndrive-network-error.js
/usr/local/ui5/js/ndrive-settings.js
/usr/local/ui5/js/ndrive-systray.js
/usr/local/ui5/js/ndrive.js

$ ndrive
ndrive: command not found

Thanks

**Comment by BoboTiG** [comment]
Hello,

With a up-to-date version, that does not work? I.e `sudo -H pip install git+https://github.com/nuxeo/nuxeo-drive.git@release-2.5.4` should work as expected (version 1.3.dev0 is extremely old :) )

**Comment by baradhili** [comment]
I'll try that - I assumed building from the highest number release would do it... :)

**Comment by baradhili** [comment]
hmm got around to trying it
sudo -H pip install git+https://github.com/nuxeo/nuxeo-drive.git@release-2.5.4
[sudo] password for bret:        
Collecting git+https://github.com/nuxeo/nuxeo-drive.git@release-2.5.4
  Cloning https://github.com/nuxeo/nuxeo-drive.git (to release-2.5.4) to /tmp/pip-xt8hZc-build
Installing collected packages: nuxeo-drive
  Found existing installation: nuxeo-drive 1.3.dev0
    Uninstalling nuxeo-drive-1.3.dev0:
      Successfully uninstalled nuxeo-drive-1.3.dev0
  Running setup.py install for nuxeo-drive ... done
Successfully installed nuxeo-drive-2.5.4
bret@Yoga:$ ndrive
ndrive: command not found
bret@Yoga:$ locate ndrive
/home/bret/.config/autostart/ndrive.desktop
/usr/local/bin/ndrive
/usr/share/doc/keepass2/Chm/help/images/b16x16_usbpendrive_unmount.png
/usr/share/icons/Humanity/devices/16/usbpendrive_unmount.svg
/usr/share/icons/Humanity/devices/24/usbpendrive_unmount.svg
/usr/share/icons/Humanity/devices/48/usbpendrive_unmount.svg
/usr/share/icons/gnome/16x16/devices/usbpendrive_unmount.png
/usr/share/icons/gnome/22x22/devices/usbpendrive_unmount.png
/usr/share/icons/gnome/24x24/devices/usbpendrive_unmount.png
/usr/share/icons/gnome/256x256/devices/usbpendrive_unmount.png
/usr/share/icons/gnome/32x32/devices/usbpendrive_unmount.png
/usr/share/icons/gnome/48x48/devices/usbpendrive_unmount.png
bret@Yoga:$ /usr/local/bin/ndrive
bash: /usr/local/bin/ndrive: No such file or directory


hmm so where did it go?

**Comment by baradhili** [comment]
walked the versions.. everything is good to 2.4.8, at 2.5.1 ndrive dissappears
running with 2.4.8 for the moment

**Comment by BoboTiG** [comment]
Hello, it should be fixed with cdcab18ec2dcdeec8a01a056444153b0db5f39b3. Thanks for the report :)
The release 2.5.6 will be released today so you can try and confirm here.
