### ISSUE TITLE
PyQt4 doesn't find QtWebKit with *.deb distribution

### ISSUE THREAD

**Issue by apeyroux** [nuxeo/nuxeo-drive#298]
Hello,

I'm looking to make a Debian package to facilitate deployment ([repo](https://github.com/apeyroux/nuxeo-drive-deb-builder)) and I discovered that PyQt4 doesn't find QtWebKit when trying to use a recent version of Ubuntu (16.10) or Debian. It seems to be a known problem with Debian and Ubuntu. 

```
  File "/opt/venvs/ndrive/local/lib/python2.7/site-packages/nxdrive/wui/dialog.py", line 11, in <module>
    from PyQt4 import QtCore, QtGui, QtNetwork, QtWebKit
```

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784513

Regards

**Comment by ataillefer** [comment]
Hi,

Yes, it is known, the solution is to migrate to PyQt5 which is planned though not yet scheduled.
You can watch the related issue in our issue tracker to be notified of its progress: https://jira.nuxeo.com/browse/NXDRIVE-692.

Making a Debian package is also something we need to work on, see https://jira.nuxeo.com/browse/NXDRIVE-351, I'm sure that your contribution could help here, I'll let @BoboTiG take over :smile:

Regards

**Comment by BoboTiG** [comment]
Hello,

As Antoine said, it is something we want to have (a DEB package for Debian based systems) but we are currently stuck with our library dependencies. Once we will be good on that point, your work would be precious to ease the .deb creation. And thanks for that!

I let the issue open as it is something asked by others too, and it will be easier to track.

**Comment by BoboTiG** [comment]
The version 4.0.0 is out (see [release notes](https://github.com/nuxeo/nuxeo-drive/releases/tag/release-4.0.0)). It greatly eases the GNU/Linux installation and use. But we still do not have a binary to deploy.

To have a working version, just do as follow (from the repository folder):
```bash
export WORKSPACE="$(pwd)"
git checkout release-4.0.0
./tools/linux/deploy_jenkins_slave.sh --install
./tools/linux/deploy_jenkins_slave.sh --start
```
Do this the first time. Then, to launch Drive, simply `./tools/linux/deploy_jenkins_slave.sh --start`.
