### ISSUE TITLE
Can't work with a proxy !

### ISSUE THREAD

**Issue by jbpotokar** [nuxeo/nuxeo-drive#30]
Hello, 

I've been installaing the version 2.0.0522, and my former parameters were not copied (:-().
After that, the connexion doesn't work, I get a message "check your url)".
When I try to do the same (exactly) without proxy, on another site, it works...
For information, my nuxeo site is an https site, and I noticed that the former version of Drive asked me what protocol I was willing to use with my proxy. This parameter doesn't exist anymore...

Regards !

**Comment by ataillefer** [comment]
Hello,

I would've expected at least the proxy mode (Manual in your case) and host name to be kept.
Anyways you're right, this new version of Nuxeo Drive doesn't handle HTTPS and proxy settings as well as the former version.
This is now tracked by https://jira.nuxeo.com/browse/NXDRIVE-344 and will be handled very soon.

Sorry for the inconvenience.

**Comment by jbpotokar** [comment]
Hi, 

Thx for this answer.I'm waiting for this correction and meanwhile I will go back to former version. 

Regards,

**Comment by ataillefer** [comment]
Hi,

https://jira.nuxeo.com/browse/NXDRIVE-344 has been fixed, can you please try latest development build:

- Windows: http://qa.nuxeo.org/jenkins/view/Drive/job/nuxeo-drive-msi/924/artifact/dist/nuxeo-drive-2.0.0608-win32.msi
- OS X: http://qa.nuxeo.org/jenkins/view/Drive/job/nuxeo-drive-dmg/995/artifact/dist/nuxeo-drive-2.0.0608-osx.dmg
- Linux: install from master branch

Thanks.

**Comment by jbpotokar** [comment]
Hello,

It's much better with the proxy. So far no problems encountered...

Regards

[cid:part1.08050704.09030106@aubay.com] Jean Baptiste POTOKAR
Directeur De la Qualité et de l'Innovation

159, rue de Silly 92100 Boulogne Billancourt

Attention, nouveau numéro  : Ligne directe : +33 (0)1 46 10 92 18

Mobile : +33 (0)6 14 81 08 17
Fax : +33 (0)1 47 61 53 21
www.aubay.com<http://www.aubay.com>

Suivez-nous sur Twitter !
https://twitter.com/aubay_dqt

Avant l'impression, pensez à l'environnement !

Le 09/06/2015 09:19, Antoine Taillefer a écrit :

Hi,

https://jira.nuxeo.com/browse/NXDRIVE-344 has been fixed, can you please try latest development build:

  *   Windows: http://qa.nuxeo.org/jenkins/view/Drive/job/nuxeo-drive-msi/924/artifact/dist/nuxeo-drive-2.0.0608-win32.msi
  *   OS X: http://qa.nuxeo.org/jenkins/view/Drive/job/nuxeo-drive-dmg/995/artifact/dist/nuxeo-drive-2.0.0608-osx.dmg
  *   Linux: install from master branch

Thanks.
