### ISSUE TITLE
Nuxeo drive fails to launch on win10 non admin

### ISSUE THREAD

**Issue by marcolefo** [nuxeo/nuxeo-drive#435]
Hello

After the update 3.0.6, nuxeo fails to launch on windows 10 with non admin privilege : 
![nuxeo](https://user-images.githubusercontent.com/6699045/37291460-f9c80f24-260e-11e8-8073-1808b2adcb7f.png)

It's working if I launch it as administrator.

Do you need more informations ?

**Comment by BoboTiG** [comment]
Hello,

The difference is that you must have non-latin characters in the full path. What is your usename for that Windows session?

**Comment by marcolefo** [comment]
Yes that's it. There was a é.
We have changed the path, it's working.

**Comment by BoboTiG** [comment]
It will be fixed with the ticket https://jira.nuxeo.com/browse/NXDRIVE-899, sorry for the inconvenience.
