### ISSUE TITLE
NX drive live edit in contentview 

### ISSUE THREAD

**Issue by BellHorn** [nuxeo/nuxeo-drive#47]
Hi,

I found a little issue on nuxeo 7.3 with nuxeo drive 2.0.818

In ''View Layout'' (content model) drive live edit icon is display with url like this: 
nxdrive://edit/http://''urlnuxeoserver''/user/ 
It's wotking and you can edit document in local and save in nuxeo server.

In content views (listing & views) liveedit icon is display with url like this:
nxedit:http://''urlnuxeoserver/nxliveedit.faces?
It's seems deprecated live edit plugin ! this url is not working and you can't edit files.

I don't know if i'ts nuxeo-drive plugin local or server side issue, so i'm sorry if I post this issue in wrong place.

thanks.

**Comment by BellRockHorn** [comment]
I looking for more about this.
It's seems is an old installation rest of plugin protocol handler in browser. So after cleanning that live edit icon in content view disapear.

But live edit with drive is not include in content listing view !!
So nuxeo drive don't remplace all function off deprecated live edit.

**Comment by ataillefer** [comment]
Yes indeed, Drive Edit icon is displayed in content views starting from 7.4, see [NXP-15617](https://jira.nuxeo.com/browse/NXP-15617).
