### ISSUE TITLE
Nuxeo Drive Connection error:please check server url

### ISSUE THREAD

**Issue by ccsilence** [nuxeo/nuxeo-drive#484]
Hi ,I have a problem about that,the same url, Nuxeo Drive In 3.0.3 version can be connected normally, but the 2.1.707 version on the url connection errors,Prompt error :Connection error:please check server url. Can you help me ~

**Comment by BoboTiG** [comment]
Hello,

This is a vert old version. If it works in 3+, then keep on that branch and use the latest 3.0.6.

Old versions are not supported, and 3.0.3 is old too :)

**Comment by ccsilence** [comment]
I works in 2+，why can't  be used?

**Comment by ccsilence** [comment]
![_20180511173211](https://user-images.githubusercontent.com/16953921/39918100-0f69dc9c-5542-11e8-8819-371b8d396978.png)
I didn't do any change on the code.The same Nuxeo server can be used in 3+ ,but cannot be used in 2 +, As shown in figure of mistakes, HTTP error.Three months ago in 2+ is normal use ,but now  in 2+ can't be used. It caused great trouble for me, I want to continue to work in 2 +, can you tell me why I can't use in 2+ and how to solve the problem.Please help me ,thank you very much :)

**Comment by BoboTiG** [comment]
You have a HTTP error 500. It is a server issue or bad informations send from Drive. It is quite hard to help without more details. Check the server logs for informations.

As I said, 2.1.707 is almost 2 years old. Why not upgrading to 3.0.6?

**Comment by ccsilence** [comment]
Thank you very much for your reply. The log from Nuxeo Drive  \.nuxeo-drive\logs\nxdrive.log. I made some development based in 2+, so I  been stay in 2+,no upgrade, do you have any solution about it?
