### ISSUE TITLE
Crash on connect on Ubuntu 15.04

### ISSUE THREAD

**Issue by doudz** [nuxeo/nuxeo-drive#53]
Successfully installed but when I click on "connect" button, the app crash 

2015-10-08 11:20:28,120 10922 139872467801856 INFO     nxdrive.utils      Removed old pid file: /home/sramage/.nuxeo-drive/nxdrive_qt.pid for stopped process 10554
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Promise(0x1753220), parent's thread is QThread(0x1766d40), current thread is QThread(0x1049240)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Promise(0x1753220), parent's thread is QThread(0x1766d40), current thread is QThread(0x1049240)
Erreur de segmentation (core dumped)

**Comment by loopingz** [comment]
Thank for your return, can you try the version 2.0.911, view your log i suppose that the new Promise system may create an issue on your computer, I'll update the code later this week so you can retry a newer version.

Regards

**Comment by loopingz** [comment]
I just added a PromiseWrapper to get read of the "QObject: Cannot create children for a parent that is in a different thread." message, if you install from master you should get the change and can confirm if the segfaul is gone.

Thank you for your help

**Comment by doudz** [comment]
Yes it works !
On the first start, sync didn't work and I got the following error:
(nautilus:4372): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(nautilus:4372): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(nautilus:4372): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(nautilus:4428): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(nautilus:4428): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(nautilus:4428): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

But on the 2nd start it works good !

Thank you
