### ISSUE TITLE
nxdrive:// protocol doesn't work on Ubuntu

### ISSUE THREAD

**Issue by doudz** [nuxeo/nuxeo-drive#54]
On Ubuntu 15.04 (and maybe other Linux), Firefox doesn't know ndrive:// protocol

**Comment by doudz** [comment]
According to this https://answers.nuxeo.com/general/q/15229d881fbf437fad75d54e101a62f3/Do-I-need-a-browser-protocol-handler-with-nuxeo-drive
we have to create the file /usr/share/applications/nxdrive-handler.desktop
```
sudo nano /usr/share/applications/nxdrive-handler.desktop
```
```
[Desktop Entry]
Name=Nuxeo Drive Protocol Handler
GenericName=Nuxeo Drive Handler
Comment=Handle NXdrive URL
Exec=ndrive %u
Terminal=false
Type=Application
MimeType=x-scheme-handler/nxdrive
```
and then 
```
sudo update-desktop-database
```

**Comment by ataillefer** [comment]
Hello,

Indeed the nxdrive protocol handler is not yet registered automatically under Linux and the solution provided in answers is the right one at the moment.

We will certainly integrate this in the Debian packaging, see https://jira.nuxeo.com/browse/NXDRIVE-351

About your ERROR, it doesn't have any consequence so you can ignore it.
Yet I've created https://jira.nuxeo.com/browse/NXDRIVE-446 to track it, we will se if we can fix it or just lower the log level.

Closing the issue.
Thanks.
