### ISSUE TITLE
sync is slow

### ISSUE THREAD

**Issue by tamasberesoebb** [nuxeo/nuxeo-drive#541]
I'm using the 3.1.1 client, and it's copying files from nuxeo to my hard drive at 4-6 Files/second.
I'm using the mac client on a 12 core 64gb imac pro (high sierra 10.13.6) , with a 70 Megabyte/second connection to our server.
I have 110000 ~300kb files on our server (< 100Gb total file size). The synch would take many days to finish.

Back when I only had thousands of only big (>500Mb) files (30Gb total size) it took less than 30 minutes to synch everything between the nuxeo server and the nuxeo synch client running on my mac.

How could I improve the sync speed for a lot of small files?

**Comment by BoboTiG** [comment]
Do you mind retry with the latest beta 4.0.0? The download link is at the bottom of https://github.com/nuxeo/nuxeo-drive/releases/tag/release-4.0.0.

**Comment by tamasberesoebb** [comment]
Sorry, I can't.

"Your server version is not compatible with Drive 4.0.0. We advise you to downgrade your Drive client to version 3.1.2 or to contact your administrator to upgrade your Nuxeo instance."
