### ISSUE TITLE
Missing QtGraphicalEffects plugin when packaged

### ISSUE THREAD

**Issue by chaselmann** [nuxeo/nuxeo-drive#544]
When opening the Settings Window after a successful installation the application crashes with a segmentation fault (see error log attached)

The cause for this error is a missing dependency in  the file "ShadowRectangle.qml". 
The missing dependency "QtGraphicalEffects 1.0" results in an empty rootObject in settings.py:init() which leads to the segmentation fault. 

After removing the import and the effect "DropwShadow" in the qml-file the client starts as expected.
The error does not occure if I start the client locally on my linux machine. 
Therefore I guess the dependency is not included in the .exe file.

[nxdrive.log](https://github.com/nuxeo/nuxeo-drive/files/2241524/nxdrive.log)

**Comment by BoboTiG** [comment]
Do you are testing the master branch? If yes, how are you setting the environment and launching Drive?
I need all details to reproduce it. Also keep in mind that the master branch is not safe to use.

**Comment by hasel** [comment]
Yes, I am testing the master branch and I am aware that this branch is not safe. 

I used the script "deploy_jenkins_slave.ps1" on a windows 10 machine to build drive with python 3.6.6 and innosetup 5.5.9. Then I lauchned Drive on windows 7 and 10 machines resulting in the same error

**Comment by BoboTiG** [comment]
OK, the thing is we did not tested the packaging yet ^^
But it will be done today, so our timings are good. Thank you for the report, we will check what option is best to fix the issue.

**Comment by BoboTiG** [comment]
You can follow the work with the ticket [NXDRIVE-1289](https://jira.nuxeo.com/browse/NXDRIVE-1289).
