### ISSUE TITLE
Python error on Windows 2003 Server

### ISSUE THREAD

**Issue by Peter2121** [nuxeo/nuxeo-drive#63]
2015-12-14 17:48:48,815 204 1192 ERROR    nxdrive.engine.workers 'module' object has no attribute 'read_directory_changes'
Traceback (most recent call last):
  File "nuxeo-drive-client\nxdrive\engine\workers.py", line 139, in run
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 93, in _execute
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 467, in _setup_watchdog
AttributeError: 'module' object has no attribute 'read_directory_changes'

No sync :(

**Comment by ataillefer** [comment]
Have you installed Nuxeo Drive from a MSI binary package? Which version of Nuxeo Drive are you running?

**Comment by Peter2121** [comment]
MSI package, 2.0.1126

Q

**Comment by ataillefer** [comment]
Can you test on a more recent version Windows, like Server 2008 or 2012?

The Nuxeo Drive MSI package is currently built on Windows Server 2012 and is known not to work on Windows XP which I guess is based on the same core version as Server 2003 (NT 5).
Minium version supported is currently 7 so I would assume it would work on Server 2008 (NT 6).

**Comment by ataillefer** [comment]
I'm also curious about the content of this directory on your Windows server :

`C:\Program Files (x86)\Nuxeo\Drive\appdata\nuxeo-drive-2.0.1126.win32\library.zip\watchdog\observers`

Does it contain `read_directory_changes.pyc`?

**Comment by Peter2121** [comment]
On Windows 2008 R2 Datacenter it does not start at all (probably, a dll lost, but no more info).
On Windows 2003 read_directory_changes.pyc is present in zip.

**Comment by ataillefer** [comment]
On 2008 you mean you have no entries in nxdrive.log? What about segfault.log and the Windows logs?

On 2003 I wonder if it could be a conflict with an existing installation of Python or the watchdog module itself.
What's the output of the following in a command line?

    python

    pip --version

If pip is installed:

    pip list

**Comment by ataillefer** [comment]
This is duplicated by https://github.com/nuxeo/nuxeo-drive/issues/68 that has been fixed, see its last comment.
